name: Test And Deoloy

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    test-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4

            - name: Install dependencies
              run: npm install

            - name: Run unit tests
              run: npm run test

            - name: Build
              run: npm run build

            - name: Remove map files
              run: rm -rf build/*.map

            - name: Copy file to server
              uses: appleboy/scp-action@v0.1.4
              with:
                host: ${{ secrets.CHILI3D_HOST }}
                username: ${{ secrets.CHILI3D_HOST_USER }}
                password: ${{ secrets.CHILI3D_HOST_PSD }}
                source: build/*
                target: /var/www/html/chili3d
                rm: true
            